### ISSUE TITLE
Create Gen2 examples

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-docs-website#102]
### Start with the `why`:

The Gen2 Pipeline Builder (https://github.com/luxonis/depthai/issues/136) allows theoretically infinite permutations of pipelines to be built.  So there is no way to do what we did with `depthai_demo.py` in Gen1 where effectively all permutations of configs can be done via CLI options.  

So for `Gen2` it will be necessary to show how the fundamental nodes can be used in easy, and simple ways.  This way, the pipeline consisting of multiple nodes can be easily built for a given application by piecing together these simple/clear examples.

Allowing the power of these permutations, but with the speed of copy/paste plugging together of examples.

### Move to the `how`:

Make a bunch of simple and easy-to-read examples of its usage, so that users can understand the API easier.

These examples will then also be integrated into automated QA, so that they will be known to work for any new releases/improvements of the DepthAI library.

### Move to the `what`:

TODO list of the examples to prepare:
- [x] Color camera preview
- [x] Mono camera preview
- [x] Mono camera + Depth map 
- [x] [Color Camera + Video encoder](https://github.com/luxonis/depthai-docs-website/issues/100)
- [x] [All streams encoding](https://github.com/luxonis/depthai-docs-website/issues/103)
- [x] Color camera + MobilenetSSD
- [x] Mono camera + MobilenetSSD
- [x] Color camera + MobilenetSSD + Depth info
- [x] Color camera + [Crop node](https://github.com/luxonis/depthai/issues/249)
- [x] Mono camera + [Crop node](https://github.com/luxonis/depthai/issues/249); PR here: https://github.com/luxonis/depthai-python/pull/184
- [x] Depth + [Crop node](https://github.com/luxonis/depthai/issues/249)

**Comment by Luxonis-Brandon** [comment]
Most of these are now implemented in this PR: https://github.com/luxonis/depthai-experiments/pull/24

**Comment by VanDavv** [comment]
Instead of experiments, we'll keep our examples in depthai-python repository, related PR here - https://github.com/luxonis/depthai-python/pull/77

**Comment by VanDavv** [comment]
Rest of the examples were implemented here -  luxonis/depthai-python#184. We can close this issue IMO
